name: Deploy Worker

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 4.9.0
          postCommands: |
            echo "*** Delete KV Entry: assets-api-data/latest_version.txt ***"
            wrangler kv key delete --binding=ASSETS_KV --preview false --remote assets-api-data/latest_version.txt
            echo "*********************************************************************"
